export const ONE_PIECE_SET_NAMES = [
  '[OP-01] Romance Dawn',
  '[OP-02] Paramount War',
  '[OP-03] Pillars of Strength',
  '[OP-04] Kingdoms of Intrigue',
  '[OP-05] Awakening of the New Era',
  '[OP-06] Wings of the Captain',
  '[OP-07] 500 Years in the Future',
  '[OP-08] Two Legends',
  '[OP-09] Emperors in the New World',
  '[OP-10] Royal Blood',
  '[OP-11] A Fist of Divine Speed',
  '[OP-12] Legacy of the Master',
  '[OP-13] Carrying On His Will',
  "[OP-14] The Azure Sea's Seven",
  "[OP-15] Adventure on Kami's Island",
  '[OP-16] The Time of Battle',
  '[EB-01] Extra Booster: Memorial Collection',
  '[EB-02] Extra Booster: Anime 25th Collection',
  '[EB-03] Extra Booster: One Piece Heroines Edition',
  '[PRB01] One Piece Card The Best Volumes 1',
  '[PRB02] One Piece Card The Best Volumes 2',
  'Promotion Card',
  'Limited Product Card'
] as const;
