export const ONE_PIECE_SET_NAMES = [
  '[OP-01] Romance Dawn',
  '[OP-02] Paramount War',
  '[OP-03] Pillars of Strength',
  '[OP-04] Kingdoms of Intrigue',
  '[OP-05] Awakening of the New Era',
  '[OP-06] Wings of the Captain',
  '[OP-07] 500 Years in the Future',
  '[OP-08] Two Legends',
  '[OP-09] Emperors in the New World',
  '[OP-10] Royal Blood',
  '[OP-11] A Fist of Divine Speed',
  '[OP-12] Legacy of the Master',
  '[OP-13] Carrying On His Will',
  "[OP-14] The Azure Sea's Seven",
  "[OP-15] Adventure on Kami's Island",
  '[OP-16] The Time of Battle',
  '[EB-01] Extra Booster: Memorial Collection',
  '[EB-02] Extra Booster: Anime 25th Collection',
  '[EB-03] Extra Booster: One Piece Heroines Edition',
  '[PRB01] One Piece Card The Best Volumes 1',
  '[PRB02] One Piece Card The Best Volumes 2',
  'ST-01: Straw Hat Crew',
  'ST-02: Worst Generation',
  'ST-03: The Seven Warlords of the Sea',
  'ST-04: Animal Kingdom Pirates',
  'ST-05: ONE PIECE FILM edition',
  'ST-06: The Navy',
  'ST-07: Big Mom Pirates',
  'ST-08: Side Monkey.D.Luffy',
  'ST-09: Side Yamato',
  'ST-10: The Three Captains',
  'ST-11: Uta (Special Deck)',
  'ST-12: Zoro & Sanji (Special Deck)',
  'ST-13: Three Brothers Ultra Deck',
  'ST-14: 3D2Y (Special Deck)',
  'ST-15: Side Monkey.D.Luffy',
  'ST-16: Side Portgas D. Ace',
  'ST-17: Side Sabo',
  'ST-18: Side Edward Newgate',
  'ST-19: Side Trafalgar Law',
  'ST-20: Side Eustass Kid',
  'ST-21: EX GEAR5',
  'ST-22: Ace & Newgate',
  'ST-23: Red Shanks',
  'ST-24: Green Jewelry Bonney',
  'ST-25: Blue Buggy',
  'ST-26: Purple/Black Monkey.D.Luffy',
  'ST-27: Black Marshall.D.Teach',
  'ST-28: GREEN/YELLOW Yamato',
  'ST-29: Egghead',
  'ST-30: EX Luffy & Ace',
  'Promotion Card',
  'Limited Product Card'
] as const;
